apiVersion: v1
kind: Service
metadata:
  #name: auth-svc
  namespace: web-apps-v1
  name: gateway-service
spec:
  selector:
    app: apigw
  ports:
    - name: port-443
      protocol: TCP
      port: 443
  type: NodePort
